version: "3"

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my_secret
      MYSQL_DATABASE: url_shorten
      MYSQL_USER: url_shorten_dev
      MYSQL_PASSWORD: my_secret
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=redis_password
    volumes:
      - redis_data:/data
    command: /bin/sh -c 'redis-server --appendonly yes --requirepass $${REDIS_PASSWORD}'

  rabbit:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
#    environment:
#      RABBITMQ_DEFAULT_USER: rabbitmq
#      RABBITMQ_DEFAULT_PASS: rabbitmq
    volumes:
      - rabbit_data:/var/lib/rabbitmq
  mongo:
    image: "mongo:4.2.16-bionic"
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: logs
    volumes:
      - mongo_data:/data/db/

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local
  rabbit_data:
    driver: local
  mongo_data:
    driver: local
